### ISSUE TITLE
Support GraphQLList on Scalar Types

### ISSUE THREAD

**Issue by rvizzari** [simtlix/gnx#14]
Currently if a type property is typed like a GraphQLList the library only support GraphQLList < Type > but if you want a GraphQLList < Scalar type > an error is throwed
e.g.
externalLocationsID: {
  type: new GraphQLList(GraphQLString),
},

ERROR:
/node_modules/@simtlix/gnx/gnx.js:180
  if (dict.types[ofType.name].inputType) {
                              ^
TypeError: Cannot read property 'inputType' of undefined

**Comment by rvizzari** [comment]
![Screenshot from 2019-12-04 10-20-57](https://user-images.githubusercontent.com/58272185/70146056-2cb66f80-1680-11ea-8720-732c56d26577.png)

**Comment by flavio-p** [comment]
Actually it is already supported. In this case that field should be exposed as embedded
```javascript
extensions: {
  relation: {
    embedded: true,
  },
},
```

**Comment by flavio-p** [comment]
You are right, I was confused by the materialize logic and even there it is not fully supported.

**Comment by flavio-p** [comment]
Fixed on #15
